//
//  UIColor+BPColors.h
//
//  Generated by Zeplin on 11/3/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import <UIKit/UIKit.h>

@interface UIColor (BPColors)

+ (UIColor *)bp_duskyBlueColor;
+ (UIColor *)bp_fadedBlueColor;
+ (UIColor *)bp_dustyOrangeColor;
+ (UIColor *)bp_charcoalGreyColor;
+ (UIColor *)bp_pinkishGreyColor;
+ (UIColor *)bp_greyishColor;
+ (UIColor *)bp_paleGreyColor;

@end
