//
//  UIColor+BPColors.m
//
//  Generated by Zeplin on 11/3/15.
//  Copyright (c) 2015 __MyCompanyName__. All rights reserved.
//

#import "UIColor+BPColors.h"

@implementation UIColor (BPColors)

+ (UIColor *)bp_duskyBlueColor {
    return [UIColor colorWithRed:67.0f / 255.0f green:87.0f / 255.0f blue:137.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)bp_fadedBlueColor {
    return [UIColor colorWithRed:119.0f / 255.0f green:148.0f / 255.0f blue:205.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)bp_dustyOrangeColor {
    return [UIColor colorWithRed:240.0f / 255.0f green:137.0f / 255.0f blue:32.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)bp_charcoalGreyColor {
    return [UIColor colorWithRed:52.0f / 255.0f green:56.0f / 255.0f blue:60.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)bp_pinkishGreyColor {
    return [UIColor colorWithWhite:193.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)bp_greyishColor {
    return [UIColor colorWithWhite:168.0f / 255.0f alpha:1.0f];
}

+ (UIColor *)bp_halfGreyishColor {
    return [UIColor colorWithWhite:168.0f / 255.0f alpha:0.5f];
}

+ (UIColor *)bp_paleGreyColor {
    return [UIColor colorWithRed:240.0f / 255.0f green:243.0f / 255.0f blue:248.0f / 255.0f alpha:1.0f];
}

@end
